### ISSUE TITLE
Add binaries to releases

### ISSUE THREAD

**Issue by hrvstr** [PraneetNeuro/Defaults#1]
Hey, first of all great project! I was looking for something like this just a couple of days ago.

Would it be possible to add binaries to the releases tab? I really don't want install Xcode just to build this app.

Thanks!

**Comment by praneet-suresh** [comment]
Hey, thanks for the feedback, appreciate it! I have added a binary and it is available for download now, check it out and let me know if you need anything else!

**Comment by hrvstr** [comment]
Thanks, just installed it and its working fine. The UX could use some work but I am sure you know that already (add a search, better support for multi-line values etc).

All in all pretty cool so far, will do some digging and see what I can find.
